{"uuid":"b62c1b75-1590-46c2-a403-a7c104e467ef","historyId":"1c7b810c8296fb1b2baf69d13eed2af6:d41d8cd98f00b204e9800998ecf8427e","status":"broken","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > Suite \"Add new moderador\" was defined but no callback was supplied. Supply a callback or explicitly skip the suite.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Suite \"Add new moderador\" was defined but no callback was supplied. Supply a callback or explicitly skip the suite.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at createInvalidArgumentTypeError (http://localhost:53276/__cypress/runner/cypress_runner.js:154932:13)\n    at createMissingArgumentError (http://localhost:53276/__cypress/runner/cypress_runner.js:154919:10)\n    at Object.create (http://localhost:53276/__cypress/runner/cypress_runner.js:161183:17)\n    at context.describe.context.context (http://localhost:53276/__cypress/runner/cypress_runner.js:160899:27)\n    at createRunnable (http://localhost:53276/__cypress/runner/cypress_runner.js:145512:31)\n    at <unknown> (http://localhost:53276/__cypress/runner/cypress_runner.js:145573:14)\n    at <unknown> (http://localhost:53276/__cypress/runner/cypress_runner.js:110838:23)\n    at tryCatcher (http://localhost:53276/__cypress/runner/cypress_runner.js:1807:23)\n    at Object.gotValue (http://localhost:53276/__cypress/runner/cypress_runner.js:6476:18)\n    at Object.gotAccum (http://localhost:53276/__cypress/runner/cypress_runner.js:6465:25)\n    at Object.tryCatcher (http://localhost:53276/__cypress/runner/cypress_runner.js:1807:23)\n    at Promise._settlePromiseFromHandler (http://localhost:53276/__cypress/runner/cypress_runner.js:1519:31)\n    at Promise._settlePromise (http://localhost:53276/__cypress/runner/cypress_runner.js:1576:18)\nFrom previous event:\n    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:53276/__cypress/runner/cypress_runner.js:3486:19)\n    at Promise._then (http://localhost:53276/__cypress/runner/cypress_runner.js:1239:17)\n    at Promise.then (http://localhost:53276/__cypress/runner/cypress_runner.js:1132:17)\n    at runScriptsFromUrls (http://localhost:53276/__cypress/runner/cypress_runner.js:110842:136)\n    at Object.runScripts (http://localhost:53276/__cypress/runner/cypress_runner.js:110883:12)\n    at $Cypress.onSpecWindow (http://localhost:53276/__cypress/runner/cypress_runner.js:40889:67)"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"}],"links":[],"start":1715751343006,"name":"An uncaught error was detected outside of a test","fullName":"cypress\\e2e\\tests\\administrador\\selectNewAdmin\\selectNewModerador.cy.js#An uncaught error was detected outside of a test","stop":1715751343017}